set nocompatible              " be iMproved, required
filetype off                  " required

" Auto-install vim-plug if not present
let s:plug_installed = 0
if has('win32')
  let s:plug_path = expand('~/vimfiles/autoload/plug.vim')
  if empty(glob(s:plug_path))
    silent !powershell -Command "
      \ New-Item -Path ~/vimfiles/autoload -ItemType Directory -Force;
      \ Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      \ -OutFile $HOME/vimfiles/autoload/plug.vim"
    let s:plug_installed = 1
  endif
else
  let s:plug_path = expand('~/.vim/autoload/plug.vim')
  if empty(glob(s:plug_path))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    let s:plug_installed = 1
  endif
endif

" Plugin section
call plug#begin()

Plug 'morhetz/gruvbox'                                        " Retro warm color scheme
Plug 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'} " Enhanced status line
Plug 'tpope/vim-commentary'                                    " Toggle comments with gc
Plug 'tmhedberg/SimpylFold'                                    " Python code folding
Plug 'neoclide/coc.nvim', {'branch': 'release'}               " LSP client for autocomplete and jump-to-definition

call plug#end()

" Auto-run PlugInstall on first install
if s:plug_installed
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" --- Gruvbox config ---
" colorscheme desert
autocmd vimenter * ++nested colorscheme gruvbox

" --- Powerline config ---
set laststatus=2              " Always show status line (required by powerline)
set showtabline=2             " Always show tab line (required by powerline)

" --- Vim native config ---
set nobackup
set noswapfile
set number
set tabstop=4
set shiftwidth=4
set expandtab
syn on
set ruler
set hls
set listchars=tab:->,trail:-
set list
set showcmd
set shortmess-=S
set backspace=indent,eol,start
set hidden
set foldmethod=syntax
set foldlevelstart=99
if has('win32')
  set guifont=FiraCode_Nerd_Font_Mono:h12
  autocmd GUIEnter * simalt ~x
elseif has('gui_macvim')
  set guifont=FiraCode\ Nerd\ Font\ Mono:h12
  set lines=999 columns=999
else
  set guifont=FiraCode\ Nerd\ Font\ Mono:h12
  set lines=999 columns=999
endif
set encoding=utf-8
setglobal fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,euc-cn,cp950,latin1

" --- coc.nvim config ---
set updatetime=300
set signcolumn=yes
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)
nnoremap <silent> K :call ShowDocumentation()<CR>
function! ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction

" --- Netrw config ---
let g:netrw_banner = 0    " Hide the help banner
let g:netrw_winsize = 25  " Set explorer width to 25%

" --- Filetype overrides ---
autocmd BufRead,BufNewFile Jenkinsfile setfiletype groovy
autocmd FileType javascript,typescript,javascriptreact,typescriptreact,groovy,xml,json,vim setlocal tabstop=2 shiftwidth=2

